media:
  # Define a media folder for images
  - name: images
    label: Images
    input: assets/images
    output: /assets/images
  # Define a media folder for videos
  - name: videos
    label: Videos
    input: assets/videos
    output: /assets/videos
content:
  - name: homepage
    label: Homepage
    type: file
    path: index.md
    fields:
      - name: layout
        label: Page layout
        type: select
        description: Will default to 'default' if none selected
        required: true
        options:
          values: [ default, home, page, post, about ]
          placeholder: Choose page layout
          default: default
      - name: title
        label: Page Title
        type: string
      - name: body
        label: Page Body
        type: rich-text
  - name: config
    label: Site Config
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website Title
        type: string
      - name: description
        label: Website Description
        type: string
        description: Will be provided for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: favicon_ico
        label: Favicon
        type: image
        description: Favicon used in the browser tab
      - name: logo
        label: Logo
        type: image
        description: Logo used in the header of the site
      - name: cover
        label: SEO Preview
        type: image
        description: Image used in the preview on social networks