media:
  # Define a media folder for images
  - name: images
    label: Images
    input: assets/images
    output: /assets/images
  # Define a media folder for videos
  - name: videos
    label: Videos
    input: assets/videos
    output: /assets/videos
content:
  - name: homepage
    label: Homepage
    type: file
    path: index.md
    fields:
      - name: layout
        label: Page layout
        type: string
        default: default
      - name: title
        label: Page title
        type: string
      - name: body
        label: Page body
        type: rich-text
  - name: config
    label: Site Config
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provided for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: remote_theme
        label: Theme
        type: string
        description: The theme to use for the site.
        default: just-the-docs/just-the-docs
      - name: cover
        label: Preview image
        type: image
        description: Image used in the preview on social networks
