media:
  # Define a media folder for images
  - name: images
    label: Images
    input: assets/images
    output: /assets/images
  # Define a media folder for videos
  - name: videos
    label: Videos
    input: assets/videos
    output: /assets/videos
