title: Rad TV Documentation
description: The documentation portal is your guide to creating and distributing video content on RadTV.com and across devices. Rad TV embraces the future of streaming and video, blockchain, VR, AI and beyond.
url: https://docs.rad.live
remote_theme: just-the-docs/just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/rad-logo-white.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.svg"

# Color scheme supports "light" (default) and "dark"
color_scheme: dark